In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
DATASET_0_1 = "../CSV/data_10time_10frame_train_0_1.csv"
DATASET_0_2 = "../CSV/data_10time_10frame_train_0_2.csv"
DATASET_1_2FACE = "../CSV/data_10time_10frame_train_1_2face.csv"
DATASET_1_book = "../CSV/data_10time_10frame_train_1_book.csv"

In [3]:
dataset_0_1 = pd.read_csv(DATASET_0_1, header=None)
dataset_0_2 = pd.read_csv(DATASET_0_2, header=None)
dataset_1_2face = pd.read_csv(DATASET_1_2FACE, header=None)
dataset_1_book = pd.read_csv(DATASET_1_book, header=None)

In [4]:
dataset_0_1.head()

0         1         2         3         4   5         6         7   \
0   1  0.755848  0.422362  6.513489  0.363843   1  0.710526  0.568100   
1   1  0.710526  0.568100  5.667634  0.979660   1  0.725000  0.770699   
2   1  0.725000  0.770699  7.021403  2.342711   1  0.659524  0.813542   
3   1  0.659524  0.813542  5.636540  2.666421   1  0.690476  0.869383   
4   1  0.690476  0.869383  6.317141  4.324977   1  0.681818  0.591067   

         8         9   ...        46        47        48        49  50  \
0  5.667634  0.979660  ...  0.725000  0.604606  5.277126  2.410918   1   
1  7.021403  2.342711  ...  0.738095  0.693548  4.842768  2.071589   1   
2  5.636540  2.666421  ...  0.800000  0.685532  5.014288  1.138532   1   
3  6.317141  4.324977  ...  0.666667  0.600486  4.957414  0.979340   1   
4  5.414141  1.557586  ...  0.750000  0.679852  4.475359  1.281701   1   

         51        52        53        54  55  
0  0.738095  0.693548  4.842768  2.071589   0  
1  0.800000  0.685532  5.014288  1.138532   0  
2  0.666667  0.600486  4.957414  0.979340   0  
3  0.750000  0.679852  4.475359  1.281701   0  
4  0.642857  0.605647  4.332279  0.996089   0  

[5 rows x 56 columns]

In [5]:
dataset = [dataset_0_1, dataset_0_2, dataset_1_2face, dataset_1_book]
dataset = pd.concat(dataset)

In [6]:
dataset.shape

(192, 56)

In [7]:
dataset.corr()

0         1         2         3         4         5         6   \
0   1.000000  0.023842  0.033404  0.232952  0.260528  0.950840  0.033585   
1   0.023842  1.000000 -0.395472 -0.141862 -0.134777  0.028502  0.501715   
2   0.033404 -0.395472  1.000000  0.506452  0.596814  0.039602 -0.222864   
3   0.232952 -0.141862  0.506452  1.000000  0.872165  0.246781 -0.138503   
4   0.260528 -0.134777  0.596814  0.872165  1.000000  0.285018 -0.099708   
5   0.950840  0.028502  0.039602  0.246781  0.285018  1.000000  0.025301   
6   0.033585  0.501715 -0.222864 -0.138503 -0.099708  0.025301  1.000000   
7   0.039229 -0.313348  0.588293  0.484493  0.476336  0.039450 -0.352503   
8   0.240877 -0.128751  0.469925  0.971245  0.843461  0.250763 -0.148741   
9   0.253025 -0.167657  0.576338  0.858599  0.929635  0.275744 -0.130737   
10  0.907841  0.048447  0.050102  0.266912  0.304620  0.954779  0.029845   
11  0.036217  0.197333 -0.129962 -0.116050 -0.062870  0.036313  0.540826   
12  0.038752 -0.067968  0.291681  0.461518  0.382022  0.041361 -0.286950   
13  0.253615 -0.089736  0.421068  0.943370  0.804512  0.259757 -0.135395   
14  0.245256 -0.132654  0.452223  0.831392  0.820113  0.269888 -0.162369   
15  0.869799  0.047581  0.056199  0.284939  0.323641  0.914770  0.048881   
16  0.044519  0.036215 -0.071315 -0.125381 -0.085829  0.046938  0.251993   
17  0.040219  0.039219  0.179294  0.409601  0.326178  0.042241 -0.053501   
18  0.260339 -0.057723  0.388666  0.913141  0.770047  0.271810 -0.096541   
19  0.245432 -0.090774  0.326276  0.798431  0.728008  0.262144 -0.130513   
20  0.835815  0.056681  0.064914  0.311171  0.361941  0.879029  0.048252   
21  0.040398  0.014594 -0.081195 -0.117166 -0.095864  0.050008  0.062785   
22  0.036899  0.108668  0.128845  0.379496  0.291978  0.040182  0.016509   
23  0.261906 -0.043358  0.363438  0.886664  0.734978  0.274321 -0.066333   
24  0.235473 -0.048170  0.251437  0.769326  0.668653  0.246860 -0.108232   
25  0.745660  0.067929  0.076264  0.331793  0.405696  0.792832  0.057911   
26  0.042023 -0.010540 -0.144677 -0.095336 -0.090242  0.055575  0.014431   
27  0.011620  0.150903  0.179969  0.350093  0.255699  0.016610  0.092689   
28  0.271080 -0.025253  0.358154  0.867181  0.708557  0.282440 -0.044989   
29  0.227293 -0.034942  0.257908  0.748468  0.634697  0.237703 -0.061091   
30  0.655505  0.078122  0.088800  0.355642  0.452026  0.706635  0.068968   
31  0.061115 -0.062088 -0.129604 -0.078799 -0.068089  0.058136 -0.014066   
32  0.008940  0.171754  0.141855  0.324708  0.232493  0.013007  0.166040   
33  0.277449 -0.012451  0.347315  0.849980  0.675532  0.288640 -0.036832   
34  0.214918 -0.016572  0.260885  0.734510  0.600752  0.227619 -0.039555   
35  0.565349  0.092175  0.099056  0.382983  0.504096  0.620438  0.078986   
36  0.077538 -0.118940 -0.079784 -0.071325 -0.011288  0.082375 -0.069287   
37  0.030332  0.133246  0.129093  0.311697  0.243148  0.033390  0.163819   
38  0.281118  0.019837  0.332546  0.842699  0.655298  0.292176 -0.023631   
39  0.199347  0.003830  0.241836  0.719452  0.574069  0.213820 -0.020213   
40  0.475194  0.085226  0.073294  0.390776  0.515339  0.534241  0.092799   
41  0.103015 -0.093240 -0.023536 -0.048554  0.005805  0.095650 -0.144493   
42  0.043399  0.063297  0.128045  0.287845  0.257262  0.047263  0.144923   
43  0.286050  0.021890  0.337714  0.839342  0.648534  0.296022  0.008651   
44  0.184400  0.001622  0.223478  0.705512  0.561039  0.198267  0.002441   
45  0.385038  0.100352  0.057824  0.393681  0.512910  0.448044  0.085969   
46  0.099117  0.015862 -0.063114 -0.042510 -0.011129  0.102397 -0.106394   
47  0.045897 -0.011841  0.193616  0.263823  0.255610  0.049549  0.084935   
48  0.289222  0.003657  0.339701  0.839691  0.642750  0.300454  0.009857   
49  0.166098 -0.057839  0.226315  0.694728  0.542809  0.182092  0.005255   
50  0.294883  0.065492  0.044206  0.390966  0.506818  0.361847  0.100836   
51  0.096902 -0.036732 -0.051269 -0.016160 -0.002164  0.09

In [8]:
X = dataset.iloc[:, 0:55].values
Y = dataset.iloc[:, 55].values

In [9]:
X

array([[ 1.        ,  0.75584795,  0.42236195, ...,  0.69354839,
         4.84276779,  2.07158899],
       [ 1.        ,  0.71052632,  0.56810036, ...,  0.68553214,
         5.01428755,  1.1385319 ],
       [ 1.        ,  0.725     ,  0.77069892, ...,  0.60048643,
         4.95741392,  0.97934011],
       ...,
       [ 1.        ,  0.79411765,  0.55359395, ...,  0.453125  ,
         0.90618745, -1.39625212],
       [ 1.        ,  0.75      ,  0.64500316, ...,  0.54661017,
         0.96954946, -1.23438087],
       [ 1.        ,  0.75      ,  0.65123754, ...,  0.54310345,
         1.1363028 , -0.86848514]])

In [10]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [11]:
from sklearn.model_selection import train_test_split 

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [13]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X)
pol_reg = LinearRegression()
pol_reg.fit(X_poly, Y)

LinearRegression()

In [19]:
pol_reg.predict(poly_reg.fit_transform([X[120]]))

array([1.])

In [16]:
import pickle
model = 'finalized_model.sav'
pickle.dump(pol_reg, open(model, 'wb'))

In [20]:
a = "[1, 2, 3]"

In [22]:
[list(a) ]

'3'

In [24]:
len(X[1])

55

In [27]:
X[1]

array([1.        , 0.71052632, 0.56810036, 5.66763351, 0.97965968,
       1.        , 0.725     , 0.77069892, 7.02140273, 2.34271132,
       1.        , 0.65952381, 0.81354167, 5.6365401 , 2.66642059,
       1.        , 0.69047619, 0.86938349, 6.31714095, 4.32497674,
       1.        , 0.68181818, 0.591067  , 5.41414117, 1.55758602,
       1.        , 0.78095238, 0.66133433, 4.88674526, 1.7694125 ,
       1.        , 0.76190476, 0.63236047, 4.617225  , 1.79077109,
       1.        , 0.87105263, 0.59190988, 4.26297011, 2.25060756,
       1.        , 0.725     , 0.60460578, 5.27712595, 2.41091804,
       1.        , 0.73809524, 0.69354839, 4.84276779, 2.07158899,
       1.        , 0.8       , 0.68553214, 5.01428755, 1.1385319 ])

In [28]:
from sklearn.linear_model import LogisticRegression
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X)
logis_pol_reg = LogistiLogistiRegression()
logis_pol_reg.fit(X_poly, Y)

LogisticRegression()

In [38]:
arr = logis_pol_reg.predict_proba(poly_reg.fit_transform([X[100]]))

In [48]:
arr[0][1]

0.9999972434159428

In [50]:
model = 'finalized_logistist_model.sav'
pickle.dump(logis_pol_reg, open(model, 'wb'))